/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package freetts;
import com.sun.speech.freetts.*;
import java.io.*;
import java.util.*;
import org.apache.pdfbox.util.PDFStreamEngine;
import org.apache.pdfbox.util.PDFTextStripper;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;
import org.apache.commons.io.IOUtils;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor; 
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Dell
 */
public class FormTTS extends javax.swing.JFrame {
       private String voice;//kevin16
       private String filename,path,line,speak,text,path1;
       File file;
       BufferedReader br = null;
       Scanner s;
       PDDocument doc2;
       FileInputStream fis;
       VoiceManager voicemanager = VoiceManager.getInstance();
    /**
     * Creates new form FormTTS
     */
    public FormTTS() {
        setSize(300, 300);
        setLayout(new FlowLayout());
        initComponents();
        JComboBox box = new JComboBox(new String[] { "First", "Second", "..." });
        box.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        tfd_text = new javax.swing.JTextField();
        btn_speech = new javax.swing.JButton();
        lbl_txt = new javax.swing.JLabel();
        lbl_file = new javax.swing.JLabel();
        jcb_file = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        lbl_voice = new javax.swing.JLabel();
        jcb_voice = new javax.swing.JComboBox();
        btn_text = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcb_format = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_speech.setText("Speak File");
        btn_speech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_speechActionPerformed(evt);
            }
        });

        lbl_txt.setText("Text");

        lbl_file.setText("File Name");

        jcb_file.setEditable(true);
        jcb_file.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "file 1", "file 2", "file 3", "file 4" }));

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        lbl_voice.setText("Select Voice");

        jcb_voice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kevin", "kevin16", "alan" }));

        btn_text.setText("Speak Text");
        btn_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_textActionPerformed(evt);
            }
        });

        jLabel1.setText("Format");

        jcb_format.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Format---", ".docx", ".pdf", ".txt", ".html" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_voice)
                        .addGap(125, 125, 125)
                        .addComponent(jcb_voice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_txt)
                        .addGap(18, 18, 18)
                        .addComponent(tfd_text, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_speech))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_file)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jcb_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_text)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_voice)
                            .addComponent(jcb_voice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_text))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(lbl_txt))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfd_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_speech)
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_file)
                            .addComponent(jcb_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jcb_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_speechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_speechActionPerformed
        try{
            voice = jcb_voice.getSelectedItem().toString();
                    
        Voice voice1 = voicemanager.getVoice(voice);
        voice1.allocate();
        
        filename = jcb_file.getSelectedItem().toString();
        path = "C:\\Users\\Dell\\Desktop\\"+filename;
        //path = "C:\\Users\\Dell\\Desktop\\garbage";
        int i=jcb_format.getSelectedIndex();
        switch(i)
        {
            case 0: voice1.speak("Sorry Sir!!!! You have not selected any file format!!! Please select!!!");
                    break;
            case 1: file = new File(path+".docx");	
                    fis = new FileInputStream(file);	
                    XWPFDocument doc1 = new XWPFDocument(fis); 
                    XWPFWordExtractor ex = new XWPFWordExtractor(doc1); 
                    String text = ex.getText();
                    textarea.setText(text);
                    voice1.speak(text);
                    break;
                
            case 2: file = new File(path+".pdf");
                    doc2 = PDDocument.load(file);
                     text = new PDFTextStripper().getText(doc2);
                     textarea.setText(text);
                    voice1.speak(text);
                    break;
               
            case 3: file = new File(path+".txt");
                    FileInputStream fisTargetFile = new FileInputStream(file);
                    text = IOUtils.toString(fisTargetFile, "UTF-8");
                    textarea.setText(text);
                    
                    voice1.speak(text);
            
                    
        }
        /*System.out.println(path1);
        br = new BufferedReader(new FileReader(path));
        while((line = br.readLine()) != null)
        {
        //voice1.speak(line);
        textarea.append(line);
        textarea.append("\n");
        }
        speak = textarea.getText();
        
        
        //voice1.speak(text);
       voice1.speak(speak);*/
        }catch(Exception ex)
        {
            //ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_speechActionPerformed

    private void btn_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_textActionPerformed
       voice = jcb_voice.getSelectedItem().toString();
        Voice voice1 = voicemanager.getVoice(voice);
        voice1.allocate();
        voice1.speak(tfd_text.getText());
    }//GEN-LAST:event_btn_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //patternList.addActionListener(this);
                new FormTTS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_speech;
    private javax.swing.JButton btn_text;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb_file;
    private javax.swing.JComboBox jcb_format;
    private javax.swing.JComboBox jcb_voice;
    private javax.swing.JLabel lbl_file;
    private javax.swing.JLabel lbl_txt;
    private javax.swing.JLabel lbl_voice;
    private javax.swing.JTextArea textarea;
    private javax.swing.JTextField tfd_text;
    // End of variables declaration//GEN-END:variables
}
